spring.application.name=triage-be3
server.port=8083
app.enabled=true
app.csas.baseUrl=https://webapi.developers.erstegroup.com/api/csas/public/sandbox/v2/rates/exchangerates?web-api-key=c52a0682-4806-4903-828f-6cc66508329e

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.group-id=triage-be3-group
spring.kafka.consumer.auto-offset-reset=earliest

app.kafka.topic=exchange-rates
app.kafka.dlt-topic=exchange-rates-dlt

# For JsonDeserializer trust packages if using default
spring.json.trusted.packages=*

# Kafka logging for troubleshooting
#logging.level.org.springframework.kafka=DEBUG
#logging.level.org.apache.kafka=DEBUG
#logging.level.org.springframework.kafka.listener=DEBUG
#logging.level.org.springframework.kafka.config=DEBUG


