spring.application.name=triage-be3
server.port=8083
app.enabled=true
app.csas.baseUrl=https://webapi.developers.erstegroup.com/api/csas/public/sandbox/v2/rates/exchangerates?web-api-key=c52a0682-4806-4903-828f-6cc66508329e


